name: Generate ASCII Artwork

on: push

jobs:
  build_job1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cowsay Program
      run: sudo apt-get install -y cowsay

    - name: Execute Cowsay CMD
      run: cowsay -f dragon "Run for cover, I am dragon.....RAWR" > dragon.txt
          
    - name: Sleep for 30 seconds
      run: sleep 30

  Test_job_2:
    # runs-on: ubuntu-latest
    steps:
    - name: Sleep for 10 seconds
      run: sleep 10

    - name: Test file Exits
      run: grep -i "dragon" dragon.txt

  deploy_job_3: 
    # runs-on: ubuntu-latest
    steps:
    - name: Read dragon file
      run: cat dragon.txt

    - name: deploy
      run: echo "deploying..."